### ISSUE TITLE
Error while iterating: missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by annette987** [drizopoulos/JM#10]
Hi,
Thank you for this amazing software. Unfortunately I am having trouble getting it to run on my own data. When I run the code below (modelled on one of your examples) I get the following error message from JointModel(): 
```
Error in while (iter < maxits && !converged) { : 
  missing value where TRUE/FALSE needed
```

This is my code:
```
library(nlme)
library(survival)
library(JM)

data_dir <- "C:/mydir/"
cox_wide <- read.csv(paste(data_dir, "data_sm_wide.csv", sep=""), header=TRUE, sep=",") 
cox_long <- read.csv(paste(data_dir, "data_sm.csv", sep=""), header=TRUE, sep=",") 

ctrl <- lmeControl(opt='optim');
bloodfit <- lme(Age ~ tstart + tstart:Urate, random=~tstart|ID, method="ML", control=ctrl, data=cox_long, na.action=na.omit)
summary(bloodfit)

coxphobject <- coxph(Surv(time=duration, event=cstatus)~Urate, data=cox_wide, x=TRUE, model=TRUE)
summary(coxphobject)

# Joint Model
ctrljm<-list(iter.EM=500)
jmfit <- jointModel(bloodfit, coxphobject, method="Cox-PH-GH", timeVar = "tstart", verbose=T, control=ctrljm)
summary(jmfit)
````
I have attached a small subset of my data. It crashes after iteration 6. I am using R 3.5.1.
Thanks for your help.
Annette
[data.zip](https://github.com/drizopoulos/JM/files/2373350/data.zip)

**Comment by drizopoulos** [comment]
Do you have the same problem with methods "piecewise-PH-aGH" or "spline-PH-aGH"?

**Comment by annette987** [comment]
Yes, a similar problem. For those two methods the error message I get is:
`Error in if (t1 || t2) { : missing value where TRUE/FALSE needed`

For piecewise-PH-aGH it happens on the 3rd iteration and for spline-PH-aGH it happens on the 1st.

**Comment by drizopoulos** [comment]
It is a scaling issue for the regression coefficients. If you transform your time to years, the model converges, i.e.,
```

cox_long$tstart <- cox_long$tstart / 365
cox_wide$duration <- cox_wide$duration / 365

ctrl <- lmeControl(opt='optim')
bloodfit <- lme(Age ~ tstart + tstart:Urate, random = ~ tstart | ID, 
                control = ctrl, data = cox_long)

coxphobject <- coxph(Surv(duration, cstatus) ~ Urate, data = cox_wide, x = TRUE)

jmfit <- jointModel(bloodfit, coxphobject, method = "piecewise-PH-aGH", 
                    timeVar = "tstart", verbose = TRUE, iter.EM = 200)
summary(jmfit)
```

**Comment by merle-bode** [comment]
I just wanted to add an answer here because I encountered this issue too. I had set up a model with an interaction of a three-level factor and age. The unit of age was already in years.
First, I encountered something like "non-finite value supplied by optim", about which somebody had formerly asked in this thread. I also encountered "Error in while (iter < maxits && !converged)" and had trouble with several methods (e.g. piecewise-PH-aGH, spline-PH-aGH).
These are things that I tried (also changed the error messages):

- Sorting my dataframes again (Clusterwise)
- Reducing covariates
- Setting control in ``lme: ctrl <- lmeControl(opt='optim')
- The final solution: Setting a zero point for age. E.g. with an age range of 10 - 20 years. 
`data$age_z​eropoint<− data$age - 10`
- I also noticed that reducing your dataframe makes a difference when you have very few observations in a cell (e.g., only one observation at age 10).

I came up with this because I had fit the models with a lower scaled time variable with plenty observations before and there were no convergence issues.


Hope this helps future readers!

**Comment by javifar** [comment]
I have elso encountered the same issue. As the other users posted before, time was already transformed in years when the error came up. I have tried a more parsimonious model, in fact, far more simple than I can afford. 
I would need to include at leaste one more covariate (age). 

`lmeFit2 <- lme(bmi ~ bs(time_years,df=3)*group + sexo , random       = ~ time_years | id2, control      = lmeControl(opt = "optim"), na.action    = na.exclude, data = xxx, method       = "REML")

coxfit <- coxph( Surv(time_years_cox, event) ~ group + sexo , model = TRUE, x = TRUE, data = cox_xxx)

**Create the event: BMI > 30**
 jointFit2 <- jointModel( lmeObject   = lmeFit2, survObject  = coxfit,  timeVar     = "time_years",  method  = "spline-PH-GH", verbose = TRUE )
`

Error in if (t1 || t2) { : missing value where TRUE/FALSE needed
