### ISSUE TITLE
Potential bug in survfitJM.jointModel.R

### ISSUE THREAD

**Issue by liuxiangyu127** [drizopoulos/JM#28]
Hi Dr. Rizopoulos,

In "survfitJM.jointModel.R" line 180, you may forget to add "Dalpha.new <- thetas.new$Dalpha".

BTW, I have another question about line 250 in "splinePHGH.fit.R". Based on the closed formula of sigma.hat, it should be the trace of Z'Zvb, why directly summing the matrix instead of summing the diagonal of the matrix?

Thanks,
Xiangyu

**Comment by drizopoulos** [comment]
Thanks I will look for the first point, probably you’re right.

For the second one, if I remember well, this is because sum(diag(ZtZ %*% vb)) is equal to sum(ZtZ * vb).

——
Professor of Biostatistics
Erasmus Medical Center Rotterdam
The Netherlands
________________________________
Από: Xiangyu Liu <notifications@github.com>
Στάλθηκε: Sunday, January 17, 2021 3:45:41 AM
Προς: drizopoulos/JM <JM@noreply.github.com>
Κοιν.: Subscribed <subscribed@noreply.github.com>
Θέμα: [drizopoulos/JM] Potential bug in survfitJM.jointModel.R (#28)


Hi Dr. Rizopoulos,

In "survfitJM.jointModel.R" line 180, you may forget to add "Dalpha.new <- thetas.new$Dalpha".

BTW, I have another question about line 250 in "splinePHGH.fit.R". Based on the closed formula of sigma.hat, it should be the trace of Z'Zvb, why directly summing the matrix instead of summing the diagonal of the matrix?

Thanks,
Xiangyu

**Comment by liuxiangyu127** [comment]
Thanks for the prompt reply. That makes sense.
